CREATE ROLE app LOGIN PASSWORD 'app_pass' CONNECTION LIMIT 10;
CREATE ROLE readonly LOGIN PASSWORD 'readonly_pass';

ALTER ROLE app SET statement_timeout = '30s';
ALTER ROLE app SET search_path = public;
ALTER ROLE readonly SET search_path = public;

GRANT CONNECT ON DATABASE "Deanery" TO admin, app, readonly;

GRANT USAGE ON SCHEMA public TO app, readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly;

-- Права на будущие объекты
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO readonly;
